]633;C]633;E;for i in {1..34};57a4fcff-c408-437b-9750-271b1a43320cCREATE DATABASE db1;
USE db1;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db2;
USE db2;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db3;
USE db3;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db4;
USE db4;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db5;
USE db5;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db6;
USE db6;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db7;
USE db7;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db8;
USE db8;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db9;
USE db9;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db10;
USE db10;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db11;
USE db11;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db12;
USE db12;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db13;
USE db13;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db14;
USE db14;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db15;
USE db15;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db16;
USE db16;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db17;
USE db17;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db18;
USE db18;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db19;
USE db19;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db20;
USE db20;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db21;
USE db21;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db22;
USE db22;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db23;
USE db23;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db24;
USE db24;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db25;
USE db25;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db26;
USE db26;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db27;
USE db27;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db28;
USE db28;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db29;
USE db29;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db30;
USE db30;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db31;
USE db31;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db32;
USE db32;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db33;
USE db33;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
CREATE DATABASE db34;
USE db34;
CREATE TABLE users(id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,username varchar(20) DEFAULT NULL,password varchar(20) DEFAULT NULL,firstname varchar(20) DEFAULT NULL,surname varchar(20) DEFAULT NULL,email varchar(255) DEFAULT NULL);
INSERT INTO users VALUES(1,'jane','jane','Jane','Doe','jane@email.com');
INSERT INTO users VALUES(2,'john','john','John','Doe','john@email.com');
