]633;C]633;E;for i in {1..34};57a4fcff-c408-437b-9750-271b1a43320cCREATE USER learning1@localhost IDENTIFIED BY 'Secure@Password@1';
GRANT ALL PRIVILEGES on db1.* to learning1@localhost;
CREATE USER learning2@localhost IDENTIFIED BY 'Secure@Password@2';
GRANT ALL PRIVILEGES on db2.* to learning2@localhost;
CREATE USER learning3@localhost IDENTIFIED BY 'Secure@Password@3';
GRANT ALL PRIVILEGES on db3.* to learning3@localhost;
CREATE USER learning4@localhost IDENTIFIED BY 'Secure@Password@4';
GRANT ALL PRIVILEGES on db4.* to learning4@localhost;
CREATE USER learning5@localhost IDENTIFIED BY 'Secure@Password@5';
GRANT ALL PRIVILEGES on db5.* to learning5@localhost;
CREATE USER learning6@localhost IDENTIFIED BY 'Secure@Password@6';
GRANT ALL PRIVILEGES on db6.* to learning6@localhost;
CREATE USER learning7@localhost IDENTIFIED BY 'Secure@Password@7';
GRANT ALL PRIVILEGES on db7.* to learning7@localhost;
CREATE USER learning8@localhost IDENTIFIED BY 'Secure@Password@8';
GRANT ALL PRIVILEGES on db8.* to learning8@localhost;
CREATE USER learning9@localhost IDENTIFIED BY 'Secure@Password@9';
GRANT ALL PRIVILEGES on db9.* to learning9@localhost;
CREATE USER learning10@localhost IDENTIFIED BY 'Secure@Password@10';
GRANT ALL PRIVILEGES on db10.* to learning10@localhost;
CREATE USER learning11@localhost IDENTIFIED BY 'Secure@Password@11';
GRANT ALL PRIVILEGES on db11.* to learning11@localhost;
CREATE USER learning12@localhost IDENTIFIED BY 'Secure@Password@12';
GRANT ALL PRIVILEGES on db12.* to learning12@localhost;
CREATE USER learning13@localhost IDENTIFIED BY 'Secure@Password@13';
GRANT ALL PRIVILEGES on db13.* to learning13@localhost;
CREATE USER learning14@localhost IDENTIFIED BY 'Secure@Password@14';
GRANT ALL PRIVILEGES on db14.* to learning14@localhost;
CREATE USER learning15@localhost IDENTIFIED BY 'Secure@Password@15';
GRANT ALL PRIVILEGES on db15.* to learning15@localhost;
CREATE USER learning16@localhost IDENTIFIED BY 'Secure@Password@16';
GRANT ALL PRIVILEGES on db16.* to learning16@localhost;
CREATE USER learning17@localhost IDENTIFIED BY 'Secure@Password@17';
GRANT ALL PRIVILEGES on db17.* to learning17@localhost;
CREATE USER learning18@localhost IDENTIFIED BY 'Secure@Password@18';
GRANT ALL PRIVILEGES on db18.* to learning18@localhost;
CREATE USER learning19@localhost IDENTIFIED BY 'Secure@Password@19';
GRANT ALL PRIVILEGES on db19.* to learning19@localhost;
CREATE USER learning20@localhost IDENTIFIED BY 'Secure@Password@20';
GRANT ALL PRIVILEGES on db20.* to learning20@localhost;
CREATE USER learning21@localhost IDENTIFIED BY 'Secure@Password@21';
GRANT ALL PRIVILEGES on db21.* to learning21@localhost;
CREATE USER learning22@localhost IDENTIFIED BY 'Secure@Password@22';
GRANT ALL PRIVILEGES on db22.* to learning22@localhost;
CREATE USER learning23@localhost IDENTIFIED BY 'Secure@Password@23';
GRANT ALL PRIVILEGES on db23.* to learning23@localhost;
CREATE USER learning24@localhost IDENTIFIED BY 'Secure@Password@24';
GRANT ALL PRIVILEGES on db24.* to learning24@localhost;
CREATE USER learning25@localhost IDENTIFIED BY 'Secure@Password@25';
GRANT ALL PRIVILEGES on db25.* to learning25@localhost;
CREATE USER learning26@localhost IDENTIFIED BY 'Secure@Password@26';
GRANT ALL PRIVILEGES on db26.* to learning26@localhost;
CREATE USER learning27@localhost IDENTIFIED BY 'Secure@Password@27';
GRANT ALL PRIVILEGES on db27.* to learning27@localhost;
CREATE USER learning28@localhost IDENTIFIED BY 'Secure@Password@28';
GRANT ALL PRIVILEGES on db28.* to learning28@localhost;
CREATE USER learning29@localhost IDENTIFIED BY 'Secure@Password@29';
GRANT ALL PRIVILEGES on db29.* to learning29@localhost;
CREATE USER learning30@localhost IDENTIFIED BY 'Secure@Password@30';
GRANT ALL PRIVILEGES on db30.* to learning30@localhost;
CREATE USER learning31@localhost IDENTIFIED BY 'Secure@Password@31';
GRANT ALL PRIVILEGES on db31.* to learning31@localhost;
CREATE USER learning32@localhost IDENTIFIED BY 'Secure@Password@32';
GRANT ALL PRIVILEGES on db32.* to learning32@localhost;
CREATE USER learning33@localhost IDENTIFIED BY 'Secure@Password@33';
GRANT ALL PRIVILEGES on db33.* to learning33@localhost;
CREATE USER learning34@localhost IDENTIFIED BY 'Secure@Password@34';
GRANT ALL PRIVILEGES on db34.* to learning34@localhost;
